provider:
  name: openfaas
  gateway: https://phxlvveba01.itplab.local
functions:
  nsxttagsync:
    lang: powercli
    handler: ./handler
    image: vmware/veba-powershell-vro:latest
    environment:
      skip_nsx_cert_check: true
      function_debug: true
      prod_environment: true
    secrets:
      - nsx-secrets
    annotations:
      topic: com.vmware.cis.tagging.detach,com.vmware.cis.tagging.attach
