provider:
  name: openfaas
  gateway: https://phxlvveba01.itplab.local
functions:
  nsxttagsync:
    lang: powercli
    handler: ./handler
    image: cmstraka/powerclicore:latest
    environment:
      function_debug: false
      skip_nsx_cert_check: true
    secrets:
      - nsx-secrets
    annotations:
      topic: com.vmware.cis.tagging.attach