provider:
  name: openfaas
  gateway: https://phxlvveba01.itplab.local
functions:
  NSXT-Tag-Sync:
    lang: powercli
    handler: ./handler
    image: cmstraka/nsxt-tag-sync
    environment:
      write_debug: true
      read_debug: true
      function_debug: false
      skip_vro_cert_check: true
    secrets:
      - vro-secrets
    annotations:
      topic: cis.tagging.detach,cis.tagging.attach
